# -*- coding: utf-8 -*-
"""footing_design_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YzoGMQesp3LW3NsJSAeRgSHILBCYgkWX
"""

# footing_app.py
import streamlit as st
import math
import pandas as pd

st.set_page_config(page_title="Optimize Rebar Splice", layout="wide")
st.title("Beam Rebar Splice Optimization")

